### ISSUE TITLE
Completed module 3 penguins Assignment

### ISSUE THREAD

**Issue by ljc3084** [ds4owd-001/md-03-assignments-ljc3084#1]
@larnsce @mianzg @sskorik01 Thank you for the assignment. However when I pipe I see this %>% instead of |> is that okay.

**Comment by sskorik01** [comment]
Hi Joseph, 

Congratulations for working through the module 3 assignments. To switch the pipe operator, you can follow the steps described here https://ds4owd-001.github.io/website/guide/
